# server/app.py
import os
import argparse
import uvicorn
from server.grader import compute_score, compute_auction_score, compute_multi_campaign_score

try:
    from openenv.core.env_server.http_server import create_app
except Exception as e:  # pragma: no cover
    raise ImportError(
        "openenv is required for the web interface. Install dependencies with '\n    uv sync\n'"
    ) from e

try:
    from ..models import AdPlatformAction, AdPlatformObservation
    from .environment import AdPlatformEnvironment
except ImportError:
    from models import AdPlatformAction, AdPlatformObservation
    from server.environment import AdPlatformEnvironment

# This dictionary lives as long as the server is running
# It maps Session IDs -> Environment Instances
_USER_ENVIRONMENTS = {}
def get_ad_platform_env(session_id: str = "default"):
    """
    OpenEnv calls this function. 
    If it's a new session, we create an env.
    If it's an existing session, we return the one we already have.
    """
    task_name = os.getenv("TASK", "budget")

    # print(f"DEBUG: Factory called for session={session_id} task={task_name}", flush=True)
    
    # This will print the actual UUID generated by OpenEnv in terminal
    # print(f"DEBUG: Request received for Session ID: {session_id}")
    
    if session_id not in _USER_ENVIRONMENTS:
        # Create a brand new instance for this specific user
        print(f"DEBUG: Creating NEW instance for {session_id}")
        _USER_ENVIRONMENTS[session_id] = AdPlatformEnvironment(task=task_name)

    env = _USER_ENVIRONMENTS[session_id]
    print(f"DEBUG: Returning env, step_count={env._state.step_count}", flush=True)
    
    # Return the instance (state is preserved inside this object)
    return _USER_ENVIRONMENTS[session_id]

# Pass the factory function
app = create_app(
    get_ad_platform_env, 
    AdPlatformAction, 
    AdPlatformObservation,
    env_name="ad_platform_env"
)

# --- Grade endpoints ---
@app.get("/grade/budget")
def grade_budget():
    env = get_ad_platform_env("default")
    grader_result = compute_score(env._state)
    score = float(max(0.01, min(0.99, grader_result["final_score"])))
    return {"score": score, "reward": score}

@app.get("/grade/auction")
def grade_auction():
    env = get_ad_platform_env("default")
    grader_result = compute_auction_score(env._state)
    score = float(max(0.01, min(0.99, grader_result["final_score"])))
    return {"score": score, "reward": score}

@app.get("/grade/dynamic_campaign")
def grade_dynamic_campaign():
    env = get_ad_platform_env("default")
    grader_result = compute_multi_campaign_score(env._state)
    score = float(max(0.01, min(0.99, grader_result["final_score"])))
    return {"score": score, "reward": score}

def main(host: str = "0.0.0.0", port: int = 8000):
    """
    Entry point for direct execution via uv run or python -m.

    This function enables running the server without Docker:
        uv run --project . server
        uv run --project . server --port 8001
        python -m ad_platform_env.server.app

    Args:
        host: Host address to bind to (default: "0.0.0.0")
        port: Port number to listen on (default: 8000)

    For production deployments, consider using uvicorn directly with
    multiple workers:
        uvicorn ad_platform_env.server.app:app --yaml-path /path/to/your/yaml.yaml --host 0.0.0.0 --port 8000
    """

    parser = argparse.ArgumentParser(description="Kube SRE Gym server")
    parser.add_argument("--port", type=int, default=port)
    parser.add_argument("--host", default=host)
    parser.add_argument("--task", choices=("budget", "auction", "dynamic_campaign"), default=None,
                        help="choose task type")
    parser.add_argument("--yaml-path", default=None,
                        help="yaml path for user/custom ad campaign profile")
    
    args = parser.parse_args()
    

    if args.task:
        os.environ["TASK"] = args.task
    if args.yaml:
        os.environ["YAML_PATH"] = args.yaml_path

    uvicorn.run(app, host=args.host, port=args.port)


if __name__ == "__main__":

    main()

